export default {
  LoginScreen: require('./LoginScreen.png'),
  WelcomeStepOne: require('./WelcomeStepOne.png'),
  WelcomeStepTwo: require('./WelcomeStepTwo.png'),
  WelcomeStepThree: require('./WelcomeStepThree.png'),
  LoginSuccess: require('./LoginSuccess.png'),
  SelectCompany: require('./SelectCompany.png'),
  ICPF: require('./ICPF.png'),
  ICPL: require('./ICPL.png'),
  ICPI: require('./ICPI.png'),
  HomeScreenBG: require('./HomeScreenBG.png'),
  iconHistory: require('./iconHistory.png'),
  iconOrder: require('./iconOrder.png'),
  iconConfirmOrder: require('./iconConfirmOrder.png'),
  news: require('./news.png'),
  emptyProduct: require('./emptyProduct.png'),
  emptyGift: require('./emptyGift.png'),
  emptyStore: require('./emptyStore.png'),
  BGStoreDetailScreen: require('./BGStoreDetailScreen.png'),
  bottomInvoice: require('./bottomInvoice.png'),
  CancelImage: require('./CancelImage.png'),
  confirmOrderImage: require('./confirmOrderImage.png'),
  timer: require('./timer.png'),
  iconCloseWhite: require('./iconCloseWhite.png'),
  bottomSlip: require('./bottomSlip.png'),
  orderSuccess: require('./orderSuccess.png'),
  emptyAvatar: require('./emptyAvatar.png'),
};
