export default {
  MenuHomeInActive: require('./MenuHomeInActive.png'),
  MenuHomeActive: require('./MenuHomeActive.png'),
  MenuHistoryInActive: require('./MenuHistoryInActive.png'),
  MenuHistoryActive: require('./MenuHistoryActive.png'),
  MenuProfileInActive: require('./MenuProfileInActive.png'),
  MenuProfileActive: require('./MenuProfileActive.png'),
  MenuNotificationInActive: require('./MenuNotificationInActive.png'),
  MenuNotificationActive: require('./MenuNotificationActive.png'),
  MenuConfirmOrderInActive: require('./MenuConfirmOrderInActive.png'),
  MenuConfirmOrderActive: require('./MenuConfirmOrderActive.png'),
  close: require('./iconClose.png'),
  flagTH: require('./flagTH.png'),
  logout: require('./logout.png'),
};
